# Automação Web e Busca de Informações com Python

#### Desafio: 

Trabalhamos em uma importadora e compramos e vendemos commodities:
- Soja, Milho, Trigo, Petróleo, etc.

Precisamos pegar na internet, de forma automática, a cotação de todas as commodites e ver se ela está abaixo do nosso preço ideal de compra. Se tiver, precisamos marcar como uma ação de compra para a equipe de operações.

Base de Dados: https://drive.google.com/drive/folders/1O9aE_Hen5smf_a6TsbVF6DM0ms4Ykj6s?usp=share_link

Para isso, vamos criar uma automação web:

- Usaremos o selenium
- Importante: baixar o webdriver

In [5]:
from selenium import webdriver


# Passo 1: Abrir o navegador
navegador = webdriver.Chrome()
navegador.get("https://www.google.com/")

In [6]:
# Passo 2: Importar a base de dados
import pandas as pd
tabela = pd.read_excel("commodities.xlsx")
display(tabela)

    Produto  Preço Ideal  Preço Atual  Comprar
0     Milho        85.32          NaN      NaN
1      Soja       163.59          NaN      NaN
2       Boi       282.20          NaN      NaN
3  Petróleo       424.37          NaN      NaN
4   Algodão       497.76          NaN      NaN
5    Açúcar       136.23          NaN      NaN
6      Café      1092.87          NaN      NaN
7      Ouro       321.77          NaN      NaN
8   Tilápia         9.05          NaN      NaN

In [ ]:
# Passo 3: Para cada produto
for linha in tabela.index:
    produto = tabela.loc[linha, "Produto"]
    produto = produto.replace("ó", "o").replace("ã", "a").replace("ç", 'c').replace('ú', 'u').replace('é', 'e').replace('á', 'a')
    link = f"https://www.melhorcambio.com/{produto}-hoje"
    navegador.get(link)
# Passo 4: Pesquisar o preço do produto    
    
    preco = navegador.find_element('xpath', '//*[@id="comercial"]').get_attribute('value')
    preco = float(preco.replace(".", "").replace(",", "."))
# Passo 5: Atualizar o preço na base de dados
    tabela.loc[linha, "Preço Atual"] = preco
    
display(tabela)

    Produto  Preço Ideal  Preço Atual  Comprar
0     Milho        85.32        64.77      NaN
1      Soja       163.59       136.57      NaN
2       Boi       282.20       329.20      NaN
3  Petróleo       424.37       437.01      NaN
4   Algodão       497.76       409.17      NaN
5    Açúcar       136.23        91.58      NaN
6      Café      1092.87      1738.26      NaN
7      Ouro       321.77       656.03      NaN
8   Tilápia         9.05         9.64      NaN

In [13]:
# Passo 6: Decidir quais produtos comprar
tabela["Comprar"] = tabela["Preço Atual"] < tabela["Preço Ideal"]
display(tabela)

# Exportar a base
tabela.to_excel("coomodities_atualizado.xlsx", index=False)

    Produto  Preço Ideal  Preço Atual  Comprar
0     Milho        85.32        64.77     True
1      Soja       163.59       136.57     True
2       Boi       282.20       329.20    False
3  Petróleo       424.37       437.01    False
4   Algodão       497.76       409.17     True
5    Açúcar       136.23        91.58     True
6      Café      1092.87      1738.26    False
7      Ouro       321.77       656.03    False
8   Tilápia         9.05         9.64    False

In [14]:
navegador.quit()